### ISSUE TITLE
Function / object naming conventions

### ISSUE THREAD

**Issue by andrechalom** [piLaboratory/GillesCom#12]
Currently, we have the functions `time` and `history`, which clash with stats::time and stats::history. We need to come up with better names to rename those functions and avoid namespace clashes.

Also, it is a good design practice to determine standard naming conventions for the functions and othe relevant objects in the package.

**Comment by piklprado** [comment]
Sure.  I'll try to keep the new names as mnemonic and informative as `time` and `history` are. Maybe `time_ellapsed`  and `trajectories` ?

**Comment by piklprado** [comment]
Also, we have to change the name of `ls.m` that can conflict with `ls` S3 methods.

**Comment by andrechalom** [comment]
I will hold this issue while waiting for the open PRs to be merged.

**Comment by andrechalom** [comment]
Changing the following:
- time() to elapsed_time() - avoids namespace clash
- history() to trajectories() - avoids namespace clash
- Interaction() to interaction_matrix() - lowercase; avoids namespace clash; also may become more self-explanatory
- ls.m() to ls_migration() - changed dot to underscore for standardization; also reduces namespace clashes with S3 methods; increased the function name in the hope that it will become more self-explanatory

We could change things like diagPlots() to diag_plots() - changed camelCase to underscores, as it is more readable. But I don't think that's necessary.

I'm leaving Init_Community and GillesComFromFile/GillesComToFile as uppercase because these are very special function in the way that they handles directly with the underlying constructor.

All of these changed already on master branch.

**Comment by andrechalom** [comment]
OK, can we close this?

**Comment by piklprado** [comment]
Ok! Can you merge into dev please?

**Comment by andrechalom** [comment]
You have already merged this changes on d090452
