### ISSUE TITLE
Add argument to give/read elapsed time in cycles or clock time

### ISSUE THREAD

**Issue by andrechalom** [piLaboratory/GillesCom#16]
Currently, bdm() uses number of cycles but the plots and results are given in terms of elapsed simulated time. We need to implement a function to give the simulated cycles, and add arguments for bdm to accept final elapsed time.

**Comment by andrechalom** [comment]
Implemented the time argument to bdm as "time to simulate in this command" as opposed to "run simulation until specified time"; the other option would be inconsistent with the "cycles" argument, which is interpreted as "cycles to be run at this step".

**Comment by andrechalom** [comment]
Currently, we don't save the "current cycle" of the snapshot in the `trajectories()`. This is needed if we want to be able to reconstruct the history of the simulation in terms of cycles instead of simulated time. Is this needed? If we don't think so, this issue is solved by 3c8d002

**Comment by Lobz** [comment]
We need to add recording of simulated time to `trajectories` as well.

**Comment by andrechalom** [comment]
Working on this on branch `rcpp_trajectories`, which is based on `rcpp_module`
