### ISSUE TITLE
Allow snapshots intervals vary in trajectory

### ISSUE THREAD

**Issue by piklprado** [piLaboratory/GillesCom#17]
`trajectory` currently returns the abundance vectors for each unity of time. For many questions it would be necessary to take snapshots at shorter intervals.

**Comment by andrechalom** [comment]
There's already a parameter for that on Init_Community, or do you need
variable intervals?

**Comment by piklprado** [comment]
Oops, haven't noticed that. Ok, regular intervals are enough.
