### ISSUE TITLE
sads evolution over time

### ISSUE THREAD

**Issue by andrechalom** [piLaboratory/GillesCom#9]
Can we make a plot representative of the sads evolution over time?

**Comment by andrechalom** [comment]
`radOverTime()` output: 

![radovertime](https://cloud.githubusercontent.com/assets/1994997/11024653/b4faed4a-8678-11e5-8df1-634734da2bb9.png)

**Comment by andrechalom** [comment]
`octavOverTime`, experimental. The idea, as above, is that older snapshots of the community are plotted in lighter gray, then darker gray, and the current shape of the sad is plotted in thick blue:

![octavovertime](https://cloud.githubusercontent.com/assets/1994997/11135360/7798466c-898b-11e5-8f52-b4b627c7da94.png)

**Comment by piklprado** [comment]
Checked and seems great. A minor tweak is to adjust the y-axis in octavOvertime to the maximum observed value in data, which is not necessarily one
